### ISSUE TITLE
Cannot start with :Veil nor on startup

### ISSUE THREAD

**Issue by simonasGit** [willothy/veil.nvim#6] opened 2023-03-25 14:51 UTC
With the Lazy configuration:
```lua
{
"willothy/veil.nvim",
    config = true,
    event = "VimEnter"
}
```
Veil doesn't appear on startup, running with `:Veil` throws
```
Error executing Lua callback: /home/basil/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:40: unexpected event
stack traceback:
        [C]: in function 'nvim_create_autocmd'
        /home/basil/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:40: in function 'display'
        /home/basil/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:188: in function </home/basil/.local/share/nvim/lazy/veil.
nvim/lua/veil.lua:187>
```

**Comment by willothy** [comment] 2023-03-25 20:09
Known issue, duplicate of #4. Closing this, will update with fixes there as I look into this. Thanks for reporting!

**Closed** 2023-03-25 20:10 UTC
Labels: duplicate
