### ISSUE TITLE
veil.lua : Buffer already exists and Unexpected event

### ISSUE THREAD

**Issue by washonrails** [willothy/veil.nvim#4] opened 2023-03-24 03:30 UTC
With the following lazy.lua file

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end

vim.cmd("set rtp+=" .. lazypath)

local lazy = require("lazy")
lazy.setup({
	...
	
	{
		'willothy/veil.nvim',
		config = true,
	},
	
     ...
})

local ui = {
	size = { width = 0.8, height = 0.8 },
	wrap = true,
	border = "single",
	icons = {
		cmd = " ",
		config = "",
		event = "",
		ft = " ",
		init = " ",
		import = " ",
		keys = " ",
		lazy = "󰒲 ",
		loaded = "●",
		not_loaded = "○",
		plugin = " ",
		runtime = " ",
		source = " ",
		start = "",
		task = "✔ ",
		list = {
			"●",
			"➜",
			"★",
			"‒",
		},
	},
}

lazy:setup()
```
the error below is thrown..

```error

Error executing lua callback: /home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:40: unexpected event
stack traceback:
Error executing lua callback: /home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:40: unexpected event
stack traceback:
	[C]: in function 'nvim_create_autocmd'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:40: in function 'display'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:180: in function </home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:178>
Error executing Lua callback: /home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:25: Vim:E95: Buffer already exists with this name.

stack traceback:
	[C]: in function 'nvim_buf_set_name'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:25: in function 'display'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:188: in function </home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:187>
	[C]: in function 'nvim_create_autocmd'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:40: in function 'display'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:180: in function </home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:178>
Error executing Lua callback: /home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:25: Vim:E95: Buffer already exists with this name.

stack traceback:
	[C]: in function 'nvim_buf_set_name'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:25: in function 'display'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:188: in function </home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:187>
```

maybe plugins conflicts?

**Comment by willothy** [comment] 2023-03-24 03:33
It may be related to calling lazy.setup twice... not sure though, I'll look into this more tomorrow. Thanks for reporting!

**Comment by washonrails** [comment] 2023-03-24 03:51
well noticed, the error thrown now is minor! Look

```lua
Error executing lua callback: /home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:40: unexpected event
stack traceback:
	[C]: in function 'nvim_create_autocmd'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:40: in function 'display'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:180: in function </home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:178>
```
	
Thank you for your support and your work!

**Comment by coopikoop** [comment] 2023-03-24 14:10
I have the same error(the smaller one). If I comment out lines 40-45 of `veil.lua`, then the dashboard will load with the `:Veil` command, but not on startup. I can't figure out any way to fix it since I don't know too much Lua, but if I figure out something I'll submit a pull request. It's just some problem with Nvim's "WinResized" event I think.

**Comment by washonrails** [comment] 2023-03-24 17:09
> I have the same error(the smaller one). If I comment out lines 40-45 of `veil.lua`, then the dashboard will load with the `:Veil` command, but not on startup. I can't figure out any way to fix it since I don't know too much Lua, but if I figure out something I'll submit a pull request. It's just some problem with Nvim's "WinResized" event I think.

WHOA , comment on lines 40 - 45 solved my problem of menu of the plugin, but now it says that this with problem in the bufferline and the telescope when i try to access configs from the main menu being that I already have the 2 plugins installed... any guesses?

Take a look
![Captura de tela de 2023-03-24 13-49-42](https://user-images.githubusercontent.com/98850074/227593699-7d533919-eb6e-4fb8-9ed2-ef05325d916f.png)

**Comment by willothy** [comment] 2023-03-24 19:24
Thanks! I'll look at the lines you commented out :) As for the Telescope fix, I'll add that to the description - it's not actually mandatory though, and it's not needed on my system, but if Telescope loads after Veil in your setup then it would be required so that Telescope loads first.

**Comment by luxus** [comment] 2023-03-26 22:34
does it veil show on startup? for me it's working with `:Veil` but not show up on start
```lua
{
    "willothy/veil.nvim",
    event = "VimEnter",
    dependencies = {
      "nvim-telescope/telescope.nvim",
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope-file-browser.nvim",
    },
    opts = {},
  }
  ```

**Comment by willothy** [comment] 2023-03-26 23:53
It should, seems like some people are having that issue though. Still looking into it. Veil is pretty experimental atm as I'm working on adding animations and such, but I should be able to get it a bit more stable soon :)

Until then, I wouldn't necessarily recommend using it as your primary dashboard.

**Comment by willothy** [comment] 2023-03-28 06:32
@coopikoop @washonrails  what version of Neovim is everyone in here using? I'm not sure why 'WinResized' is showing as an invalid event, it seems to work fine for me although I'm on nightly. I'll try installing some older versions and testing it out.

**Comment by washonrails** [comment] 2023-03-28 19:45
@coopikoop i'm using NVIM v0.8.3

complete info : NVIM v0.8.3
Build type: None
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -UNDEBUG -g -ffile-prefix-map=/builddir/neovim-0.8.3/build=. -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/neovim-0.8.3/build/cmake.config -I/builddir/neovim-0.8.3/src -I/usr/include -I/builddir/neovim-0.8.3/build/src/nvim/auto -I/builddir/neovim-0.8.3/build/include
Compilado por void-buildslave@a-fsn-de

Features: +acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/usr/share/nvim"

**Comment by coopikoop** [comment] 2023-03-28 19:50
Mine is the same
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

**Comment by willothy** [comment] 2023-03-28 22:26
Thanks for the info! That's very helpful, I'll install that version to test. 

I'm working on quite a large patch right now. The fix for this is already in it, I'm just finishing up the new feature which is somewhat interlinked with the fix.

Essentially, the entire menu will be rendered with virtual text, and will use a "virtual cursor" to navigate within the window. By virtual cursor, I mean that the default cursor is hidden, and instead interactive components have a Focused hlgroup that determines what a "hovered" element looks like (default is the Visual group). The vcursor will automatically jump between interactive components.

This should be a bit faster, and also allows state / animations to be used in interactive sections as they can be redrawn without repeatedly editing the buffer.

Stay tuned!

**Comment by willothy** [comment] 2023-03-29 06:10
Confirmed working on `v0.8.4-dev-2+gb1ae775de`, should work on `v0.8.3` as well.

**Comment by willothy** [comment] 2023-03-29 07:30
@luxus does your Neovim version not support `blend` in highlights?

**Closed** 2023-03-29 07:44 UTC
